services:
 frontend:
  image: node:25-alpine3.22
  command: sh -c "npm install && npm run dev"
  ports:
   - 127.0.0.1:5173:5173
  working_dir: /frontend
  networks:
   - hidden
   - public
  volumes:
   - ./frontend:/frontend
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.whoami.rule=Host(`projekt-bazy-io.docker.localhost`)"
   - "traefik.http.routers.whoami.entrypoints=web"
 backend:
  image: node:25-alpine3.22
  command: sh -c "npm install && npx prisma generate && npx tsx watch index.ts"
  ports:
   - 127.0.0.1:3000:3000
  working_dir: /backend
  networks:
   - hidden
  volumes:
   - ./backend:/backend
  environment:
   DATABASE_URL: postgresql://user:pass@127.0.0.1:5432/data?pgbouncer=true
   DIRECT_URL: postgresql://user:pass@127.0.0.1:5432/data
 db:
  image: postgres:18.3-alpine3.23
  restart: always
  shm: 128mb
  networks:
   - hidden
  volumes:
   - ./postgres-data:/var/lib/postgresql/data
  environment:
   POSTGRES_PASSWORD: pass
   POSTGRES_USER: user
   POSTGRES_DB: data
 proxy:
  image: traefik:v3.7.0
  networks:
   - public
  restart: unless-stopped
  security_opt:
   - no-new-privileges:true
  ports:
   - 8080:8080
   - 80:80
  command:
   - "--providers.docker=true"
   - "--providers.docker.exposedbydefault=false"
   - "--providers.docker.network=proxy"
   - "--entryPoints.web.address=:80"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock

networks:
 hidden:
  name: hidden
 public:
  name: public
  